services:
  chroma:
    image: chromadb/chroma:0.5.3 # Nome corretto dell'immagine
    container_name: chroma
    expose:
      - "8000"
    volumes:
      - ./data/vector_db:/chroma/chroma
    environment:
      - IS_PERSISTENT=TRUE
      - ANONYMIZED_TELEMETRY=FALSE
      - PERSIST_DIRECTORY=/chroma/chroma  # ← stesso path del volume
    networks:
      - db-network
    restart: unless-stopped

  rag-system:
    build:
      context: ./app
      dockerfile: Dockerfiles/rag/Dockerfile
    container_name: rag-system
    stdin_open: true
    tty: true

    expose:
        - "8001"
    volumes:
      - ./app:/app
      - ./data/raw:/app/data/raw
      - ./models_cache:/root/.cache/huggingface

    networks:
      - app-network
      - db-network
    depends_on:
      - chroma
    env_file:
      - .env

  ollama:
    image: ollama/ollama:latest
    container_name: ollama
    volumes:
      - ./ollama_data:/root/.ollama
    expose:
      - "11434"
    networks:
      - db-network
      - app-network
    restart: unless-stopped

  jupyter:
    build:
      context: ./app
      dockerfile: Dockerfiles/jupyter/Dockerfile
    container_name: jupyter
    ports:
      - "8888:8888"
    volumes:
      - .:/home/jovyan/work
    environment:
      - JUPYTER_ENABLE_LAB=yes
      - PYTHONPATH=/home/jovyan/work
      - HF_HOME=/home/jovyan/work/models_cache        # ← aggiungi
      - TRANSFORMERS_CACHE=/home/jovyan/work/models_cache  # ← aggiung
      - ANONYMIZED_TELEMETRY=FALSE
    networks:
      - app-network
      - db-network
    restart: unless-stopped

networks:
  app-network:
    driver: bridge
  db-network:
    driver: bridge